name: CI/CD with Asana Integration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies and start app
      run: |
        cd dairy-farm-app
        npm install
        npm run start

    - name: Update Asana task from commit message
      env:
        ASANA_TOKEN: ${{ secrets.ASANA_TOKEN }}
      run: |
        COMMITS=$(git log -1 --pretty=format:"%s%n%b")
        echo "Commit message: $COMMITS"

        # Extract the Asana Task ID (expects format ASANA_TASK:1234567890)
        ASANA_TASK_ID=$(echo "$COMMITS" | grep -o 'ASANA_TASK:[0-9]*' | cut -d: -f2 | head -n 1)

        if [ -n "$ASANA_TASK_ID" ]; then
          echo "Found Asana Task ID: $ASANA_TASK_ID"

          curl -X POST "https://app.asana.com/api/1.0/tasks/$ASANA_TASK_ID/stories" \
            -H "Authorization: Bearer $ASANA_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"text\": \"Code pushed to main: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}\"}"
        else
          echo "No Asana Task ID found in commit message."
        fi
